name: ProcessWatch
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  ProcessWatch:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
        excludes:
          - Info.plist
    resources:
      - path: Sources/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.greyson.ProcessWatch
        PRODUCT_NAME: ProcessWatch
        INFOPLIST_FILE: Sources/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Supporting/ProcessWatch-Bridging-Header.h
        HEADER_SEARCH_PATHS: "$(SRCROOT)/Sources/Supporting"
        OTHER_LDFLAGS: "-lproc"
        ENABLE_APP_SANDBOX: NO
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
